# Generated by Django 2.2 on 2019-04-16 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sekail', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_store',
            field=models.BooleanField(default=True),
        ),
    ]
