# Generated by Django 2.2 on 2019-04-16 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sekail', '0002_auto_20190416_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_store',
            field=models.BooleanField(default=False),
        ),
    ]
