# Generated by Django 2.2 on 2019-04-16 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sekail', '0003_auto_20190416_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='iemi_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
