# Generated by Django 2.2 on 2019-04-16 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sekail', '0004_auto_20190416_1003'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='national_id',
            new_name='phone_number',
        ),
        migrations.RenameField(
            model_name='store',
            old_name='store_id',
            new_name='phone_number',
        ),
    ]
